### ISSUE TITLE
Not an issue, instead a suggestion

### ISSUE THREAD

**Issue by TheSunIsADeadlyLaser** [pluto7073/PlutosCoffeeMod-Fabric#1]
Culinaire Integration/Collaboration pack would be an interesting addon or maybe a main mod update 👀
I'd love to see Pluto's kettle model there or maybe a proper Coffee Maker thingy which name I always forget

Not demanding it, no way I'm swooping this low, but they seem to be quite a good mod team and their tea is a lovely addition.
Besides, you collaborating will also solve the Coffee-Tea conflict in the peacefull-est way

**Comment by pluto7073** [comment]
I am actually currently working on an actual Coffee Machine, and a better, more customizable way to make coffee with NBT Instead of Seperate Items. As of Tea, I have a tea mod that I am working on Integrating into this one, I just have to update it first. Thanks for the suggestion, and I am also working on a mod that adds a bunch of new foods, which of course will interact with this mod if you are using both.
